export let SwapLocations = [
    "Student Union",
    "University Place",
    "Alan Gilbert Learning Commons (LC)",
    "Main Library",
    "Samuel Alexander Building Foyer",
    "George Kenyon Hall",
    "Hulme & Burkhardt",
    "St Anselm",
    "Owens Park",
    "Liberty Park",
    "Woolton Hall",
    "Dalton-Ellis",
    "Canterbury Court",
    "Ashburne & Sheavyn",
    "Whitworth Park",
    "Oak House",
    "Richmond Park",
    "Unsworth Park",
    "Weston Hall",
    "Wright Robinson",
]