export const Brands = [
  'Abercrombie & Fitch',
  'Acne Studios',
  'Adidas',
  'Alexander McQueen',
  'Alexander Wang',
  'Alfred Dunhill',
  'Alice Olivia',
  'AllSaints',
  'Anthropologie',
  'Anti Social Social Club',
  'Armani',
  'ASOS',
  'Balenciaga',
  'Berghaus',
  'Bershka',
  'Billionaire Boys Club',
  'Boohoo',
  'Bottega Veneta',
  'Brandi Melville',
  'Burberry',
  'C&A',
  'Calvin Klein',
  'Canada Goose',
  'Carhartt',
  'CAT',
  'Celine',
  'Champion',
  'Chanel',
  'Charlotte Russe',
  'Chloe',
  'Christian Louboutin',
  'Clarks',
  'Club Monaco',
  'COACH',
  'Columbia',
  'Converse',
  'COS',
  'Crocs',
  'Diane von Furstenberg',
  'Diesel',
  'Dior',
  'DKNY',
  'Dolce & Gabbana',
  'Dope',
  'Dr. Martens',
  'Dune',
  'Ecko',
  'Ed Hardy',
  'Ermenegildo Zegna',
  'Escada',
  'Esprit',
  'Fashion Nova',
  'Fear of God',
  'Fendi',
  'Fila',
  'FIVE FOXes',
  'Forever 21',
  'Fred Perry',
  'Free People',
  'French Connection',
  'G-Star',
  'Gap',
  'Giorgio Armani',
  'Giuseppe Zanotti',
  'Givenchy',
  'Golf Wang',
  'Gucci',
  'Guess',
  'H&M',
  'Hermes',
  'Herschel Supply & Co.',
  'Hollister',
  'Huf',
  'Hunter',
  'HUGO BOSS',
  'Inditex',
  'Isabel Marant',
  'IVY PARK',
  'Jack Wills',
  'Jimmy Choo',
  'Juicy Couture',
  'Kappa',
  'Kate Spade',
  'Kenzo',
  'Kith',
  'Kurt Geiger',
  'Lacoste',
  'Levi’s',
  'Lilly Pulitzer',
  'Lipsy',
  'Loewe',
  'Longchamp',
  'Louis Vuitton',
  'Maje',
  'Mango',
  'Manolo Blahnik',
  'Marc Jacobs',
  'Massimo Dutti',
  'MaxMara',
  'MCM',
  'Metersbonwe',
  'Michael Kors',
  'Miss Selfridge',
  'Missguided',
  'Miu Miu',
  'Moncler',
  'Moschino',
  'Mulberry',
  'Nasty Gal',
  'New Balance',
  'New Look',
  'Next',
  'Nike',
  'Oakley',
  'Obey',
  'Oh Polly',
  'Off-White',
  'Office',
  'Old Navy',
  'Oscar de La Renta',
  'Other',
  'Oysho',
  'Palace',
  'Patagonia',
  'Paul Smith',
  'Peacocks',
  'Phillip Lim',
  'Prada',
  'PrettyLittleThing',
  'Primark',
  'Proenza Schouler',
  'Pull & Bear',
  'PUMA',
  'rag & bone',
  'Rainbow Shops',
  'Ralph Lauren',
  'Rebecca Minkoff',
  'Reebok',
  'Renner',
  'Reiss',
  'Riachuelo',
  'River Island',
  'Roberto Cavalli',
  'Saint Laurent',
  'Salvatore Ferragamo',
  'Sandro',
  'Schuh',
  'Shasa',
  'Stella McCartney',
  'Stone Island',
  'Stradivarius (clothing brand)',
  'Stuart Weitzman',
  'Superdry',
  'Supreme',
  'Theory',
  'The North Face',
  'Tod`s',
  'Tom Ford',
  'Tommy Hilfiger',
  'Topshop',
  'Tory Burch',
  'Timberland',
  'Ugg',
  'Umbro',
  'Under Armour',
  'Uniqlo',
  'United Colors of Benetton',
  'Urban Outfitters',
  'Uterqüe',
  'Unbranded',
  'Valentino',
  'Vans',
  'Versace',
  'Vince',
  'Vintage',
  'Yeezy',
  'ZaraBally',
  'Balmain',
  'BAPE',
  'Barbour',
  'Ben Sherman',
  'Bench',
  'Berghaus',
  'Bershka',
  'Billionaire Boys Club',
  'Boohoo',
  'Bottega Veneta',
  'Brandi Melville',
  'Burberry',
  'C&A',
  'Calvin Klein',
  'Canada Goose',
  'Carhartt',
  'CAT',
  'Celine',
  'Champion',
  'Chanel',
  'Charlotte Russe',
  'Chloe',
  'Christian Louboutin',
  'Clarks',
  'Club Monaco',
  'COACH',
  'Columbia',
  'Converse',
  'COS',
  'Crocs',
  'Diane von Furstenberg',
  'Diesel',
  'Dior',
  'DKNY',
  'Dolce & Gabbana',
  'Dope',
  'Dr. Martens',
  'Dune',
  'Ecko',
  'Ed Hardy',
  'Ermenegildo Zegna',
  'Escada',
  'Esprit',
  'Fashion Nova',
  'Fear of God',
  'Fendi',
  'Fila',
  'FIVE FOXes',
  'Forever 21',
  'Fred Perry',
  'Free People',
  'French Connection',
  'G-Star',
  'Gap',
  'Giorgio Armani',
  'Giuseppe Zanotti',
  'Givenchy',
  'Golf Wang',
  'Gucci',
  'Guess',
  'H&M',
  'Hermes',
  'Herschel Supply & Co.',
  'Hollister',
  'Huf',
  'Hunter',
  'HUGO BOSS',
  'Inditex',
  'Isabel Marant',
  'IVY PARK',
  'Jack Wills',
  'Jimmy Choo',
  'Juicy Couture',
  'Kappa',
  'Kate S0pade',
  'Kenzo',
  'Kith',
  'Kurt Geiger',
  'Lacoste',
  'Levi’s',
  'Lilly Pulitzer',
  'Lipsy',
  'Loewe',
  'Longchamp',
  'Louis Vuitton',
  'Maje',
  'Mango',
  'Manolo Blahnik',
  'Marc Jacobs',
  'Massimo Dutti',
  'MaxMara',
  'MCM',
  'Metersbonwe',
  'Michael Kors',
  'Miss Selfridge',
  'Missguided',
  'Miu Miu',
  'Moncler',
  'Moschino',
  'Mulberry',
  'Nasty Gal',
  'New Balance',
  'New Look',
  'Next',
  'Nike',
  'Oakley',
  'Obey',
  'Oh Polly',
  'Off-White',
  'Office',
  'Old Navy',
  'Oscar de La Renta',
  'Other',
  'Oysho',
  'Palace',
  'Patagonia',
  'Paul Smith',
  'Peacocks',
  'Phillip Lim',
  'Prada',
  'PrettyLittleThing',
  'Primark',
  'Proenza Schouler',
  'Pull & Bear',
  'PUMA',
  'rag & bone',
  'Rainbow Shops',
  'Ralph Lauren',
  'Rebecca Minkoff',
  'Reebok',
  'Renner',
  'Reiss',
  'Riachuelo',
  'River Island',
  'Roberto Cavalli',
  'Saint Laurent',
  'Salvatore Ferragamo',
  'Sandro',
  'Schuh',
  'Shasa',
  'Stella McCartney',
  'Stone Island',
  'Stradivarius (clothing brand)',
  'Stuart Weitzman',
  'Superdry',
  'Supreme',
  'Theory',
  'The North Face',
  'Tod s',
  'Tom Ford',
  'Tommy Hilfiger',
  'Topshop',
  'Tory Burch',
  'Timberland',
  'Ugg',
  'Umbro',
  'Under Armour',
  'Uniqlo',
  'United Colors of Benetton',
  'Urban Outfitters',
  'Uterqüe',
  'Unbranded',
  'Valentino',
  'Vans',
  'Versace',
  'Vince',
  'Vintage',
  'Yeezy',
  'Zara',
];
