export const ProductTypes = {
  group1: [
    'Athletic Shorts',
    'Bikini Set',
    'Blazer',
    'Blouse',
    'Bodycon Dress',
    'Bomber Jacket',
    'Cardigan',
    'Coat',
    'Cycling Shorts',
    'Denin Jacket',
    'Denim Shorts',
    'Dungarees, Flared Jeans',
    'High Waisted Jeans',
    'Hoodie',
    'Joggers',
    'Jumper',
    'Knitwear',
    'Long Jumpsuit',
    'Long Sleeve Shirt',
    'Loose Jeans',
    'Low Rise Jeans',
    'Maxi Dress',
    'Maxi Skirt',
    'Midi Dress',
    'Midi Skirt',
    'Mini Skirt',
    'Mom Jeans',
    'Other Jacket',
    'Party Dress',
    'Shirt',
    'Short Dress',
    'Short Jumpsuit',
    'Skinny Jeans',
    'Straight Jeans',
    'Sweatshirt',
    'Swimsuit',
    'T - shirt',
    'Trousers',
    'Turtleneck',
    'Vest',
    'Wrap Dress'
  ],
  group2: [
    'Backpack',
    'Bag'
  ],
  group3: ['Belt'],
  group4: [
    'Gloves',
    'Lingerie',
    'Tights'
  ],
  group5: [
    'Boots',
    'Flip Flops',
    'High Heels',
    'Loafers',
    'Sandals',
    'Slippers',
    'Trainers'
  ],
  group6: ['Hat or Cap', 'Scarf'],
  group7: ['Hair accessories', 'Jewellery', 'Socks', 'Wallet or Purse'],
  group8: ['Other'],
};

