export const ProductTypes = [
  'Athletic Shorts',
  'Backpack',
  'Bag',
  'Belt',
  'Bikini Set',
  'Blazer',
  'Blouse',
  'Bodycon Dress',
  'Bomber Jacket',
  'Boots',
  'Cardigan',
  'Coat',
  'Cycling Shorts',
  'Denim Jacket',
  'Denim Shorts',
  'Dungarees',
  'Flared Jeans',
  'Flip Flops',
  'Gloves',
  'Hair Accessories',
  'Hat or Cap',
  'High Heels',
  'High Waisted Jeans',
  'Hoodie',
  'Jewellery',
  'Joggers',
  'Jumper',
  'Knitwear',
  'Lingerie',
  'Loafers',
  'Long Jumpsuit',
  'Long Sleeve Shirt',
  'Loose Jeans',
  'Low Rise Jeans',
  'Maxi Dress',
  'Maxi Skirt',
  'Midi Dress',
  'Midi Skirt',
  'Mini Skirt',
  'Mom Jeans',
  'Other',
  'Other Jacket',
  'Party Dress',
  'Sandals',
  'Scarf',
  'Shirt',
  'Short Dress',
  'Short Jumpsuit',
  'Skinny Jeans',
  'Slippers',
  'Socks',
  'Straight Jeans',
  'Sweatshirt',
  'Swimsuit',
  'T-shirt',
  'Tights',
  'Trainers',
  'Trousers',
  'Turtleneck',
  'Vest',
  'Wallet or Purse',
  'Wrap Dress',
];
